Repository vmware-tanzu/tanzu-cli, pull requests merged in 2023-05, with the labels that each got.

#243 Update broken link
  docs/plugindev/migrate.md
Labels: cla-not-required

#237 Pass a TANZU_BIN env var to plugins
  docs/plugindev/README.md
  hack/central-repo/fakeplugin.sh
  hack/central-repo/registry-content.bz2
  pkg/cli/plugin_cmd.go
  pkg/cli/plugin_cmd_test.go
Labels: cla-not-required

#230 Bug fix : Add version in the error messages for plugin lifecycle methods
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
  test/e2e/framework/framework.go
  test/e2e/plugin_sync/plugin_sync_lifecycle_test.go
Labels: cla-not-required

#124 CLI Coexistence Tests using E2E framework
  .github/workflows/cli-coexistence_tests.yaml
  .gitignore
  Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  go.work.sum
  hack/scripts/process-ginkgo-test-results.sh
  test/e2e/cli_lifecycle/init_version_cmds_test.go
  test/e2e/coexistence/README.md
  test/e2e/coexistence/cli_coexistence_suite_test.go
  test/e2e/coexistence/cli_coexistence_test.go
  test/e2e/context/context_lifecycle_helper.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/cli_lifecycle_operations.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_helper.go
Labels: cla-not-required

#247 Update templates for new plugin projects
  cmd/plugin/builder/template/plugintemplates/Makefile.tmpl
  cmd/plugin/builder/template/plugintemplates/common.mk.tmpl
  cmd/plugin/builder/template/plugintemplates/dotgolangci.txt.tmpl
  cmd/plugin/builder/template/plugintemplates/github_workflow_build.yaml.tmpl
  cmd/plugin/builder/template/plugintemplates/github_workflow_release.yaml.tmpl
  cmd/plugin/builder/template/plugintemplates/gitlab-ci.yaml.tmpl
  cmd/plugin/builder/template/plugintemplates/gomod.tmpl
  cmd/plugin/builder/template/plugintemplates/main.go.tmpl
  cmd/plugin/builder/template/plugintemplates/main_test.go.tmpl
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  cmd/plugin/builder/template/plugintemplates/templates.go
  cmd/plugin/builder/template/plugintemplates/tools.go.tmpl
  cmd/plugin/builder/template/root.go
  cmd/plugin/builder/template/target.go
Labels: cla-not-required

#248 Add signature verification of the inventory image before downloading plugin bundle
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/cosignhelper/sigverifier/signature_verification.go
  pkg/cosignhelper/sigverifier/signature_verification_test.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
Labels: cla-not-required

#246 bug fix: e2e plugin life cycle tests
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required

#251 Fix the e2e tests
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
Labels: cla-not-required

#250 Update to use runtime v0.90.0-alpha.1
  docs/plugindev/README.md
  docs/plugindev/migrate.md
  go.mod
  go.sum
  go.work.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cla-not-required

#245 Implement air-gapped E2E tests for plugin bundle download, upload and lifecycle
  Makefile
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/airgapped/plugins.go
  test/e2e/framework/framework.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_sync/plugin_sync_lifecycle_suite_test.go
Labels: cla-not-required

#253 Update gitlab config file
  cmd/plugin/builder/template/plugintemplates/gitlab-ci.yaml.tmpl
  cmd/plugin/builder/template/plugintemplates/gitlab-ci.yml.tmpl
  cmd/plugin/builder/template/plugintemplates/templates.go
  cmd/plugin/builder/template/root.go
Labels: cla-not-required

#252 Add documentation for CLI interaction with registry having self-signed CA
  docs/full/README.md
Labels: cla-not-required

#254 Add documentation for installing plugins in air-gapped environments
  docs/full/README.md
  docs/quickstart/install.md
Labels: cla-not-required

#256 Add TANZU_CLI_STANDALONE_OVER_CONTEXT_PLUGINS to prioritize standalone over context plugins
  docs/plugindev/README.md
  pkg/constants/env_variables.go
  pkg/pluginsupplier/plugin_supplier.go
  pkg/pluginsupplier/plugin_supplier_test.go
Labels: cla-not-required

#229 E2E: plugin sync e2e test implementation for TMC target
  pkg/constants/env_variables.go
  pkg/pluginmanager/default_discoveries.go
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/coexistence/cli_coexistence_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/cmd_exec_operations.go
  test/e2e/framework/config_lifecycle_operations.go
  test/e2e/framework/context_create_operations.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/output_handling.go
  test/e2e/framework/plugin_operations.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_helper.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#244 E2E: stress tests for context and config
  test/e2e/Makefile
  test/e2e/config/config_init_feature_flag_stress_test.go
  test/e2e/config/config_server_test.go
  test/e2e/config/config_suite_test.go
  test/e2e/context/context_lifecycle_helper.go
  test/e2e/context/k8s/context_k8s_lifecycle_stress_test.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/k8s/context_suite_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_stress_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/context/tmc/tmc_suite_test.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#262 Remove mention of filter for search
  pkg/command/plugin_search.go
Labels: cla-not-required

#268 TMC endpoint validation for context create
  pkg/pluginmanager/default_discoveries.go
  pkg/pluginmanager/default_discoveries_test.go
Labels: cla-not-required

#275 Specify a fixed tag for the registry:2 image
  Makefile
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  plugin-tooling.mk
  test/e2e/framework/plugin_registry.go
Labels: cla-not-required

#264 Fix vcs status error by allowing passing in build go flags to plugin builder
  cmd/plugin/builder/command/cli_compile.go
  cmd/plugin/builder/plugin.go
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  plugin-tooling.mk
Labels: cla-not-required

#271 Remove the "--self-managed" flag in "tanzu context create" command
  pkg/command/context.go
  pkg/constants/env_variables.go
Labels: cla-not-required

#272 Fix the "tanzu plugin upload-bundle" to use the docker login config to upload the bundle to a registry which requires credentials
  pkg/carvelhelpers/fetcher.go
  pkg/registry/client.go
Labels: cla-not-required

#235 Bug fix: Add Validators for prompts to not allow bad data into context and login commands
  go.mod
  go.sum
  go.work.sum
  pkg/command/ceip_participation.go
  pkg/command/context.go
  pkg/command/plugin_search_test.go
Labels: cla-not-required

#278 Fix CEIP short description
  pkg/command/ceip_participation.go
Labels: cla-not-required

#269 Sync should throw an error for any error in plugin discovery
  pkg/command/context.go
  pkg/pluginmanager/manager.go
  test/e2e/context/tmc/context_tmc_lifecycle_stress_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/context_create_operations.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#280 Fix the latency issue caused after not using anonymous user while reading or downloading image from registry
  pkg/carvelhelpers/fetcher.go
  pkg/registry/client.go
Labels: cla-not-required

#282 Remove unnecessary operations of "tanzu init"
  pkg/catalog/catalog.go
  pkg/command/init.go
Labels: cla-not-required

#267 Add --name to plugin group search
  pkg/airgapped/plugin_bundle_download.go
  pkg/command/plugin_group.go
  pkg/discovery/interface.go
  pkg/discovery/interface_test.go
  pkg/discovery/oci.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/discovery/oci_test.go
  pkg/plugininventory/plugin_inventory.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
Labels: cla-not-required

#277 plugin list order should be consistent
  pkg/command/plugin.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#281 Plugin describe json support
  pkg/command/plugin.go
  pkg/command/plugin_test.go
  test/e2e/coexistence/cli_coexistence_test.go
  test/e2e/framework/config_lifecycle_operations.go
  test/e2e/framework/context_lifecycle_operations.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/output_handling.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required

#270 Add plugin group versioning and description
  cmd/plugin/builder/README.md
  cmd/plugin/builder/inventory/inventory_plugin_group.go
  cmd/plugin/builder/inventory/inventory_plugin_group_test.go
  cmd/plugin/builder/inventory_plugin.go
  cmd/plugin/builder/inventory_plugin_group.go
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  docs/dev/centralized_plugin_discovery.md
  docs/full/README.md
  docs/quickstart/install.md
  docs/quickstart/quickstart.md
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/command/plugin.go
  pkg/command/plugin_bundle.go
  pkg/command/plugin_group.go
  pkg/discovery/interface.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/types.go
  pkg/plugininventory/data/sqlite/create_tables.sql
  pkg/plugininventory/data/sqlite/plugin_inventory_metadata_tables.sql
  pkg/plugininventory/plugin_inventory.go
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_metadata.go
  pkg/plugininventory/sqlite_inventory_metadata_test.go
  pkg/plugininventory/sqlite_inventory_test.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
  plugin-tooling.mk
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_test.go
  test/e2e/coexistence/cli_coexistence_suite_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/output_handling.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
Labels: cla-not-required

#286 Fail command if EULA terms are not accepted
  pkg/command/eula_test.go
  pkg/command/root.go
Labels: cla-not-required, area/ux

#288 show e2e test results
  .github/workflows/cli-coexistence_tests.yaml
  .github/workflows/cli_core_e2e_test.yaml
  .gitignore
  hack/scripts/process-ginkgo-test-results.sh
  test/e2e/Makefile
  test/e2e/cli_lifecycle/cli_lifecycle_suite_test.go
  test/e2e/coexistence/cli_coexistence_suite_test.go
  test/e2e/context/k8s/context_suite_test.go
  test/e2e/context/tmc/tmc_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_suite_test.go
Labels: cla-not-required

#285 Add the "plugin group get" command
  docs/quickstart/quickstart.md
  pkg/command/plugin_group.go
Labels: cla-not-required

#289 Add backward compatibility support for private customer plugins
  pkg/config/defaults.go
  pkg/config/defaults_test.go
  pkg/constants/env_variables.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#291 Update installation docs
  docs/quickstart/install.md
Labels: cla-not-required

#290 Support using SHAs in the plugin binary references
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/airgapped/helper.go
  pkg/registry/helpers.go
  pkg/registry/helpers_test.go
Labels: cla-not-required

#293 Update to use runtime v0.90.0-alpha.2
  docs/plugindev/README.md
  docs/plugindev/migrate.md
  go.mod
  go.sum
Labels: cla-not-required

#292 Update to use runtime v0.90.0-alpha.2
  docs/plugindev/README.md
  docs/plugindev/migrate.md
  go.mod
  go.sum
Labels: cla-not-required

#287 tmc and k8s contexts e2e tests
  test/e2e/context/tmc/context_tmc_k8s_contexts_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_stress_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/context/tmc/tmc_suite_test.go
  test/e2e/framework/context_lifecycle_operations.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
Labels: cla-not-required

#297 Use the group description of the latest version
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_test.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
Labels: cla-not-required

#296 Enable completion when installing with APT and RPM
  hack/apt/build_package.sh
  hack/rpm/tanzu-cli.spec
Labels: cla-not-required

#304 Add an official public key to the inventory image signature verification
  pkg/cosignhelper/cosignverify.go
  pkg/cosignhelper/tanzu_cli_cert.go
Labels: cla-not-required

#302 Deprecate legacy config apis
  go.mod
  go.sum
  go.work.sum
  pkg/command/config.go
  pkg/config/bom.go
  pkg/config/defaults.go
  pkg/config/edition.go
Labels: cla-not-required

#308 Verify plugin source before accepting to update it
  pkg/command/discovery_source.go
  pkg/command/discovery_source_test.go
  pkg/discovery/oci_dbbacked.go
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
Labels: cla-not-required

#307 Rename column for "plugin group get" and update E2E tests
  pkg/command/plugin_group.go
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/output_handling.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_helper.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
Labels: cla-not-required

#301 Bug Fix: Add plugin binary File empty check in build plugins step
  cmd/plugin/builder/helpers/helper.go
  cmd/plugin/builder/helpers/helpers_test.go
  cmd/plugin/builder/plugin/build-packages.go
  pkg/utils/files.go
Labels: cla-not-required

#310 Fix E2E tests
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/coexistence/cli_coexistence_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_suite_test.go
Labels: cla-not-required

#273 Use `docker` interface to build plugin OCI images as part of `tanzu builder plugin build-package`
  cmd/plugin/builder/README.md
  cmd/plugin/builder/docker/docker.go
  cmd/plugin/builder/docker/interface.go
  cmd/plugin/builder/fakes/imgpkgwrapper.go
  cmd/plugin/builder/imgpkg/imgpkg.go
  cmd/plugin/builder/imgpkg/interface.go
  cmd/plugin/builder/inventory/inventory_plugin.go
  cmd/plugin/builder/inventory/inventory_plugin_group.go
  cmd/plugin/builder/inventory_plugin.go
  cmd/plugin/builder/inventory_plugin_group.go
  cmd/plugin/builder/plugin.go
  cmd/plugin/builder/plugin/build-packages.go
  cmd/plugin/builder/plugin/helpers.go
  cmd/plugin/builder/plugin/publish-packages.go
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  docs/cli/commands/tanzu_builder_plugin_build-package.md
  pkg/plugininventory/sqlite_inventory.go
  pkg/utils/files.go
  plugin-tooling.mk
Labels: cla-not-required

#257 Update the installation instruction link in release notes
  .github/workflows/release.yaml
Labels: cla-not-required, area/docs

#305 Add detailed help for plugin commands
  pkg/command/plugin.go
  pkg/command/plugin_bundle.go
  pkg/command/plugin_search_test.go
Labels: cla-not-required

#315 Have "plugin clean" also clean the inventory cache
  pkg/common/defaults.go
  pkg/discovery/oci.go
  pkg/discovery/oci_dbbacked.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
Labels: cla-not-required

#313 e2e tests for completion command
  test/e2e/cli_lifecycle/cli_completion_cmd_test.go
  test/e2e/cli_lifecycle/cli_lifecycle_suite_test.go
  test/e2e/cli_lifecycle/init_version_cmds_test.go
  test/e2e/framework/cli_lifecycle_operations.go
  test/e2e/framework/context_create_operations.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_constants.go
  test/e2e/framework/framework_helper.go
Labels: cla-not-required

#311 Fix corrupt catalog cache issue when plugins were installed with old CLI
  pkg/catalog/cleanup.go
  pkg/cli/plugin_cmd.go
  pkg/command/root.go
  pkg/common/constants.go
Labels: cla-not-required

#320 Show the group version when installing from latest
  pkg/command/plugin.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
Labels: cla-not-required

#322 Don't download plugin if binary already present
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#321 Add printouts about plugins being downloaded for "plugin download-bundle"
  pkg/airgapped/plugin_bundle_download.go
Labels: cla-not-required

#324 Deprecate `tanzu builder cli compile` and `tanzu builder publish` commands
  cmd/plugin/builder/cli.go
  cmd/plugin/builder/publish.go
Labels: cla-not-required

#318 Add changes to ignore the `tanzu pinniped-auth` command for EULA and CEIP prompts
  pkg/command/root.go
Labels: cla-not-required

#309 Add changes to use pinniped-auth plugin to get pinniped kubeconfig for TKG/TKGs clusters
  hack/central-repo/generate-central.sh
  pkg/auth/tkg/cluster_pinniped_info.go
  pkg/auth/tkg/cluster_pinniped_info_test.go
  pkg/auth/tkg/kube_config.go
  pkg/auth/tkg/kube_config_test.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/context_tkg_helper.go
  pkg/command/context_tkg_helper_test.go
  pkg/command/login.go
  pkg/command/login_test.go
  pkg/cosignhelper/cosignverify.go
  pkg/fakes/certs/fake-ca.crt
Labels: cla-not-required

#325 Update to use runtime v0.90.0-beta.0
  docs/plugindev/README.md
  docs/plugindev/migrate.md
  go.mod
  go.sum
Labels: cla-not-required

#326 Update release-0.90 to use runtime v0.90.0-beta.0
  docs/plugindev/README.md
  docs/plugindev/migrate.md
  go.mod
  go.sum
Labels: cla-not-required

#314 Switch the default plugin repository to production central plugin repository
  pkg/constants/defaults.go
Labels: cla-not-required

#317 plugin list should show plugins even when specific context has issues
  pkg/command/plugin.go
  pkg/command/plugin_search.go
  pkg/pluginmanager/manager.go
  test/e2e/coexistence/cli_coexistence_test.go
  test/e2e/context/tmc/context_tmc_k8s_contexts_test.go
  test/e2e/framework/cli_lifecycle_operations.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_helper.go
Labels: cla-not-required

#306 nil check for pointers
  pkg/auth/csp/grpc.go
  pkg/command/config.go
  pkg/command/context.go
  pkg/command/login.go
  pkg/config/features.go
  pkg/pluginmanager/default_discoveries.go
  test/e2e/framework/config_lifecycle_operations.go
Labels: cla-not-required

#327 E2E tmc test cases fix
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#328 E2E Context tests random failure fix
  test/e2e/context/k8s/context_k8s_lifecycle_stress_test.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/k8s/context_k8s_suite_test.go
  test/e2e/context/tmc/context_tmc_k8s_contexts_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_stress_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_suite_test.go
Labels: cla-not-required
