Repository vmware-tanzu/tanzu-cli, pull requests merged in 2023-10, with the labels that each got.

#510 Update tanzu context list to include UCP data
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/fakes/config/tanzu_config_ng.yaml
Labels: cla-not-required

#499 Run E2E test for `tanzu plugin upload-bundle` against authenticated registry
  Makefile
  hack/central-repo/.gitignore
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required

#504 Show log message on plugin installation based on various plugin installation states
  pkg/pluginmanager/manager.go
  pkg/pluginsupplier/plugin_supplier.go
  pkg/pluginsupplier/plugin_supplier_test.go
Labels: cla-not-required

#517 Adjust example for "context create"
  pkg/command/context.go
  pkg/constants/env_variables.go
Labels: cla-not-required

#522 Remove trailing space
  pkg/command/context.go
Labels: cla-not-required

#519 Dynamic shell completion for miscellaneous commands
  pkg/command/ceip_participation.go
  pkg/command/ceip_participation_test.go
  pkg/command/completion.go
  pkg/command/completion_test.go
  pkg/command/doc.go
  pkg/command/doc_test.go
  pkg/command/init.go
  pkg/command/init_test.go
  pkg/command/version.go
  pkg/command/version_test.go
Labels: cla-not-required

#528 Add missing .PHONY target
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  plugin-tooling.mk
Labels: cla-not-required

#531 Fix typo in output when deleting a context
  pkg/command/context.go
Labels: cla-not-required

#532 Add note regarding Tanzu CLI golang API level compatibility
  docs/full/policy.md
Labels: cla-not-required

#530 Do not use the CLIs sub-command help for the builder plugin
  cmd/plugin/builder/inventory.go
  cmd/plugin/builder/inventory_plugin.go
  cmd/plugin/builder/inventory_plugin_group.go
  cmd/plugin/builder/plugin.go
Labels: cla-not-required

#501 Dynamic shell completion for the context cmds
  pkg/command/completion_helper.go
  pkg/command/completion_helper_test.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/plugin.go
  pkg/command/plugin_search.go
  pkg/utils/common.go
Labels: cla-not-required

#536 Migrate to use NewOutputWriterWithOptions API for context list
  go.mod
  go.sum
  pkg/command/ceip_participation.go
  pkg/command/cert.go
  pkg/command/config.go
  pkg/command/context.go
  pkg/command/discovery_source.go
  pkg/command/plugin.go
  pkg/command/plugin_group.go
  pkg/command/plugin_search.go
Labels: cla-not-required

#539 Update `tanzu context create --type` UX to align `--type` options with other commands
  pkg/command/context.go
  pkg/command/context_test.go
Labels: cla-not-required

#513 Dynamic shell completion for the plugin cmds
  pkg/command/completion_helper.go
  pkg/command/context.go
  pkg/command/discovery_source.go
  pkg/command/discovery_source_test.go
  pkg/command/plugin.go
  pkg/command/plugin_bundle.go
  pkg/command/plugin_bundle_test.go
  pkg/command/plugin_group.go
  pkg/command/plugin_group_test.go
  pkg/command/plugin_helper_test.go
  pkg/command/plugin_search.go
  pkg/command/plugin_search_test.go
  pkg/command/plugin_test.go
  pkg/fakes/plugins/darwin/amd64/global/builder/v0.0.0/tanzu-builder-darwin_amd64
  pkg/fakes/plugins/darwin/amd64/kubernetes/secret/v0.0.0/tanzu-secret-darwin_amd64
  pkg/fakes/plugins/darwin/amd64/kubernetes/secret/v0.0.0/test/tanzu-secret-test-darwin_amd64
  pkg/fakes/plugins/darwin/amd64/plugin_manifest.yaml
  pkg/fakes/plugins/darwin/arm64/global/builder/v0.0.0/tanzu-builder-darwin_arm64
  pkg/fakes/plugins/darwin/arm64/kubernetes/secret/v0.0.0/tanzu-secret-darwin_arm64
  pkg/fakes/plugins/darwin/arm64/kubernetes/secret/v0.0.0/test/tanzu-secret-test-darwin_arm64
  pkg/fakes/plugins/darwin/arm64/plugin_manifest.yaml
  pkg/fakes/plugins/linux/amd64/global/builder/v0.0.0/tanzu-builder-linux_amd64
  pkg/fakes/plugins/linux/amd64/kubernetes/secret/v0.0.0/tanzu-secret-linux_amd64
  pkg/fakes/plugins/linux/amd64/kubernetes/secret/v0.0.0/test/tanzu-secret-test-linux_amd64
  pkg/fakes/plugins/linux/amd64/plugin_manifest.yaml
  pkg/fakes/plugins/linux/arm64/global/builder/v0.0.0/tanzu-builder-linux_arm64
  pkg/fakes/plugins/linux/arm64/kubernetes/secret/v0.0.0/tanzu-secret-linux_arm64
  pkg/fakes/plugins/linux/arm64/kubernetes/secret/v0.0.0/test/tanzu-secret-test-linux_arm64
  pkg/fakes/plugins/linux/arm64/plugin_manifest.yaml
  pkg/fakes/plugins/plugin_group_manifest.yaml
  pkg/fakes/plugins/plugin_manifest.yaml
  pkg/fakes/plugins/windows/amd64/plugin_manifest.yaml
Labels: cla-not-required

#540 Add arch type to the output of "tanzu version"
  pkg/command/version.go
  pkg/command/version_test.go
Labels: cla-not-required

#535 Kubeconfig path changes in context create
  pkg/auth/tkg/kube_config.go
  pkg/auth/tkg/kube_config_test.go
  pkg/command/context.go
  pkg/command/context_tkg_helper_test.go
  pkg/command/login.go
Labels: cla-not-required

#542 Delete the kubeconfig pertained to the CLI context during "tanzu context delete" command execution
  pkg/auth/utils/kubeconfig/kubeconfig.go
  pkg/auth/utils/kubeconfig/kubeconfig_test.go
  pkg/command/context.go
  pkg/command/context_test.go
Labels: cla-not-required

#520 Dynamic shell completion for the tanzu config command tree
  pkg/command/cert.go
  pkg/command/cert_test.go
  pkg/command/config.go
  pkg/command/config_test.go
  pkg/command/eula.go
  pkg/command/eula_test.go
Labels: cla-not-required

#524 Update Plugin Runtime and Decouple the Target association with the Context commands
  go.mod
  go.sum
  go.work.sum
  pkg/auth/csp/grpc_test.go
  pkg/command/completion_helper.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/plugin.go
  pkg/pluginmanager/default_discoveries.go
  pkg/pluginmanager/manager.go
  pkg/pluginsupplier/plugin_supplier.go
  pkg/telemetry/metrics_helper.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required

#545 Update to use version 1.1.0-alpha.0 of runtime
  go.mod
  go.sum
  test/e2e/framework/go.mod
  test/e2e/framework/go.sum
Labels: cla-not-required

#546 fix for interface conversion at metrics helper
  pkg/telemetry/metrics_helper.go
Labels: cla-not-required

#547 Cherry pick: fix for interface conversion at metrics helper
  pkg/telemetry/metrics_helper.go
Labels: cla-not-required

#537 Add support for "tanzu plugin delete all --target"
  go.work.sum
  pkg/command/plugin.go
  pkg/command/plugin_test.go
  pkg/command/root_test.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_helper_test.go
  pkg/pluginmanager/manager_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required

#548 Update EULA and CEIP prompt messages with hint on how to avoid the interactive prompt
  pkg/config/config.go
Labels: cla-not-required

#526 Clarify the output of "plugin group get --all" and add unit tests
  pkg/command/plugin_group.go
  pkg/command/plugin_group_test.go
  pkg/command/plugin_helper_test.go
  pkg/plugininventory/plugin_inventory.go
Labels: cla-not-required

#518 E2E: config the input data
  go.mod
  go.work.sum
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/config_data/cli.tanzu.vmware.com_cliplugins.yaml
  test/e2e/config_data/input_data.yaml
  test/e2e/framework/framework.go
  test/e2e/framework/framework_constants.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
  test/e2e/util/config.go
Labels: cla-not-required

#551 Cleanup file created by the unit test
  pkg/auth/utils/kubeconfig/kubeconfig_test.go
Labels: cla-not-required

#549 Use `uninstall` as a `tanzu plugin delete` alternative and make it primary command
  docs/full/cli-architecture.md
  docs/quickstart/quickstart.md
  pkg/command/plugin.go
  pkg/command/plugin_test.go
  pkg/pluginmanager/manager.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required

#544 Update `tanzu config set/unset` help message
  pkg/command/config.go
  test/e2e/config/config_init_feature_flag_test.go
  test/e2e/framework/config_lifecycle_operations.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required

#559 Unhide --all flag for plugin group get
  pkg/command/plugin_group.go
Labels: cla-not-required

#550 Update telemetry metrics collection to account for application-engine context type
  pkg/telemetry/client.go
  pkg/telemetry/client_test.go
  pkg/telemetry/metrics_helper.go
  pkg/telemetry/metrics_helper_test.go
Labels: cla-not-required

#552 Add ActiveHelp when no completions are provided
  pkg/command/ceip_participation.go
  pkg/command/ceip_participation_test.go
  pkg/command/cert.go
  pkg/command/cert_test.go
  pkg/command/completion.go
  pkg/command/completion_test.go
  pkg/command/config.go
  pkg/command/config_test.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/discovery_source.go
  pkg/command/discovery_source_test.go
  pkg/command/doc.go
  pkg/command/doc_test.go
  pkg/command/eula.go
  pkg/command/eula_test.go
  pkg/command/init.go
  pkg/command/init_test.go
  pkg/command/plugin.go
  pkg/command/plugin_bundle.go
  pkg/command/plugin_bundle_test.go
  pkg/command/plugin_group.go
  pkg/command/plugin_group_test.go
  pkg/command/plugin_search.go
  pkg/command/plugin_search_test.go
  pkg/command/plugin_test.go
  pkg/command/version.go
  pkg/command/version_test.go
Labels: cla-not-required

#553 Automatically suggest `--target` when a plugin name is ambiguous
  pkg/command/plugin.go
  pkg/command/plugin_test.go
Labels: cla-not-required

#555 Complete valid values for --target
  pkg/command/plugin.go
  pkg/command/plugin_helper_test.go
  pkg/command/plugin_test.go
Labels: cla-not-required

#558 Add note in documentation about authenticated registry support
  docs/quickstart/install.md
Labels: cla-not-required, area/docs

#560 Implements reprompt on updated EULA
  go.mod
  go.sum
  pkg/command/eula.go
  pkg/command/eula_test.go
  pkg/config/config.go
Labels: cla-not-required

#561 Show a core command's short text in ActiveHelp when completing arguments
  pkg/command/ceip_participation_test.go
  pkg/command/cert_test.go
  pkg/command/completion_test.go
  pkg/command/config_test.go
  pkg/command/context_test.go
  pkg/command/discovery_source_test.go
  pkg/command/doc_test.go
  pkg/command/eula_test.go
  pkg/command/init_test.go
  pkg/command/plugin_bundle_test.go
  pkg/command/plugin_group_test.go
  pkg/command/plugin_search_test.go
  pkg/command/plugin_test.go
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/command/version_test.go
Labels: cla-not-required

#565 Include aliases in the main help
  pkg/cli/usage.go
Labels: cla-not-required

#557 Update documentation to add `ContextType` terminology and update `Target` concept
  docs/full/cli-architecture.md
  docs/full/context-scoped-plugins.md
Labels: cla-not-required, area/docs

#562 Rename 'application-engine' and 'TAE' naming references with 'tanzu'
  go.mod
  go.sum
  go.work.sum
  pkg/auth/tanzu/kubeconfig.go
  pkg/auth/tanzu/kubeconfig_test.go
  pkg/command/completion_helper.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/root.go
  pkg/fakes/config/kubeconfig1.yaml
  pkg/fakes/config/tanzu_config_ng.yaml
  pkg/fakes/config/tanzu_config_ng_2.yaml
  pkg/telemetry/metrics_helper.go
  pkg/telemetry/metrics_helper_test.go
  pkg/utils/common.go
  pkg/utils/common_test.go
Labels: cla-not-required

#556 Enhance UX for plugin group install
  pkg/command/plugin.go
  pkg/command/plugin_group.go
  pkg/pluginmanager/manager.go
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_test.go
  test/e2e/cataloge2e/catalog_update_parallel_test.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#508 E2E tests for Sample plugin
  .github/workflows/cli_core_e2e_sample-plugin.yaml
  go.work
  test/sample-plugin/Makefile
  test/sample-plugin/cmd/plugin/sample-plugin/README.md
  test/sample-plugin/cmd/plugin/sample-plugin/main.go
  test/sample-plugin/cmd/plugin/sample-plugin/test/e2e/framework_functionality/plugin_functionality_suite_test.go
  test/sample-plugin/cmd/plugin/sample-plugin/test/e2e/framework_functionality/plugin_functionality_test.go
  test/sample-plugin/cmd/plugin/sample-plugin/test/e2e/plugin_functionality/plugin_functionality_suite_test.go
  test/sample-plugin/cmd/plugin/sample-plugin/test/e2e/plugin_functionality/plugin_functionality_test.go
  test/sample-plugin/cmd/plugin/sample-plugin/test/e2e/testresults/plugin_functionality_results.json
  test/sample-plugin/cmd/plugin/sample-plugin/test/main.go
  test/sample-plugin/common.mk
  test/sample-plugin/go.mod
  test/sample-plugin/go.sum
  test/sample-plugin/plugin-tooling.mk
Labels: cla-not-required

#566 Add some examples to tanzu config set
  pkg/command/config.go
Labels: cla-not-required, area/ux

#570 Document global plugins and co-existence
  docs/quickstart/quickstart.md
Labels: cla-not-required, doc-impact

#563 UX update for 'context use' to list plugins will be installed
  pkg/command/context.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/context_lifecycle_operations.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#572 UX: Enhance UX for `plugin sync` to list plugins before installation
  pkg/command/context.go
  pkg/command/plugin.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
Labels: cla-not-required

#579 Rename --ca-certificate option to --ca-cert in "tanzu config cert add" and "tanzu config cert update" commands
  Makefile
  docs/cli/commands/tanzu_config_cert_add.md
  docs/cli/commands/tanzu_config_cert_update.md
  docs/quickstart/install.md
  pkg/command/cert.go
  pkg/command/cert_test.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required, docs-impact

#583 Adjust empty line delimiter for essential plugins
  docs/quickstart/install.md
  pkg/pluginmanager/essentials.go
Labels: cla-not-required

#584 Don't use logging for user output
  pkg/command/plugin.go
  pkg/command/plugin_group.go
  pkg/command/plugin_group_test.go
Labels: cla-not-required

#581 Update outdated development README.md
  docs/dev/README.md
Labels: cla-not-required

#575 Replace 'plugin delete' with 'plugin uninstall'
  pkg/command/plugin_test.go
  test/e2e/framework/framework_constants.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#576 Update doc for Mac ARM64 support
  docs/plugindev/README.md
Labels: cla-not-required

#586 Note about advance support for the 'tanzu' context
  pkg/command/context.go
Labels: cla-not-required

#578 Improve documentation for shell completion
  docs/dev/README.md
  docs/full/README.md
  docs/plugindev/README.md
  docs/quickstart/quickstart.md
  pkg/command/completion.go
  pkg/command/completion_helper.go
  pkg/command/root.go
  pkg/constants/env_variables.go
Labels: cla-not-required

#585 Update context create help for TMC(mission-control)
  pkg/command/context.go
Labels: cla-not-required

#587 Add URL scheme validation for TMC endpoint while creating context
  pkg/command/context.go
  pkg/command/context_test.go
Labels: cla-not-required

#589 TMC E2E tests fix - ignore endpoint validation
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/constants/env_variables.go
Labels: cla-not-required

#590 Fix the tanzu login issue when the "tanzu" context is created with context create command
  pkg/command/login.go
Labels: cla-not-required

#588 Update TANZU_API_TOKEN help message
  pkg/command/context.go
  pkg/command/login.go
  pkg/constants/env_variables.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_suite_test.go
  test/e2e/framework/context_create_operations.go
Labels: cla-not-required, docs-impact
