Repository vmware-tanzu/tanzu-cli, pull requests merged in 2023-04, with the labels that each got.

#154 Updates to `plugindev` documents
  docs/plugindev/README.md
Labels: cla-not-required

#146 Additional discoveries are automatically trusted
  pkg/config/defaults.go
  pkg/config/defaults_test.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#150 Use a Go native SQLite library
  go.mod
  go.sum
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_test.go
Labels: cla-not-required, alpha-testing-prereq

#148 Use caching for plugin discovery images
  pkg/discovery/oci_dbbacked.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required, alpha-testing-prereq

#151 Some minor fixes in the E2E tests
  test/e2e/config/config_server_test.go
  test/e2e/context/context_k8s_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/cmd_exec_operations.go
  test/e2e/framework/context_create_operations.go
Labels: cla-not-required

#143 Add CEIP Opt-In support
  Makefile
  go.mod
  go.sum
  pkg/command/ceip_participation.go
  pkg/command/ceip_participation_test.go
  pkg/command/plugin_test.go
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/config/config.go
  pkg/constants/env_variables.go
Labels: cla-not-required, alpha-testing-prereq

#160 Modify `PluginDescriptor` update instructions in the plugindev docs
  docs/plugindev/README.md
Labels: cla-not-required, area/docs

#162 update tanzu-plugin-runtime dependency
  go.mod
  go.sum
Labels: cla-not-required, alpha-testing-prereq

#163 Update go.sum
  go.sum
Labels: cla-not-required

#164 Improve user message
  pkg/discovery/oci_dbbacked.go
Labels: cla-not-required

#157 Add policy documentation for Tanzu CLI
  docs/dev/README.md
  docs/dev/deprecation.md
  docs/full/deprecation.md
  docs/full/policy.md
  docs/plugindev/README.md
  docs/plugindev/style_guide.md
Labels: cla-not-required, area/docs

#158 Add docs regarding context-scoped plugin installation
  docs/design/context-aware-plugin-discovery-design.md
  docs/design/images/context-aware-plugin-discovery-design.png
  docs/full/README.md
  docs/full/context-scoped-plugins.md
  docs/proposals/README.md
  docs/quickstart/quickstart.md
Labels: cla-not-required, area/docs

#168 Remove `discovery-source` documentation and Minor documentation fixes
  docs/full/README.md
  docs/plugindev/migrate.md
  docs/plugindev/style_guide.md
Labels: cla-not-required, area/docs

#167 Update installation instructions
  README.md
  docs/quickstart/install.md
Labels: cla-not-required, area/docs

#169 Minor updates migrate docs
  docs/plugindev/migrate.md
Labels: cla-not-required, area/docs

#171 Update quickstart and context-scope plugin doc
  docs/full/context-scoped-plugins.md
  docs/quickstart/quickstart.md
Labels: cla-not-required, area/docs

#174 Minor doc fixes in `docs/plguindev`
  docs/dev/README.md
  docs/plugindev/README.md
  docs/plugindev/build_stage_styleguide_checklist.md
  docs/plugindev/contract.md
  docs/release/release-notes.md
Labels: cla-not-required, area/docs

#170 Makefile updates to refactor cross-build
  Makefile
Labels: cla-not-required, area/build

#175 Doc fixes in `docs/full/README.md` and `docs/plugindev/taxonomy.md`
  docs/full/README.md
  docs/plugindev/taxonomy.md
Labels: cla-not-required

#176 Doc fixes docs/full/README.md, docs/plugindev/README.md, docs/full/cl…
  docs/full/README.md
  docs/full/cli-wordlist.yml
  docs/plugindev/README.md
Labels: cla-not-required

#179 E2E tests github badge update
  README.md
Labels: cla-not-required

#178 Fix Docs in Target and Context Management section under `docs/full/README.md`
  README.md
  docs/full/README.md
  docs/plugindev/design_stage_styleguide_checklist.md
Labels: cla-not-required

#173 Unify the tanzu installation locations
  pkg/common/defaults.go
Labels: cla-not-required

#166 Add design doc for secure plugin installation by CLI
  docs/full/README.md
  docs/proposals/secure-plugin-installation-design.md
Labels: cla-not-required, area/docs

#181 Add release workflow
  .github/workflows/release.yaml
Labels: cla-not-required, area/build

#180 Add doc for the centralized OCI discovery
  docs/dev/README.md
  docs/dev/centralized_plugin_discovery.md
  docs/dev/images/centralized_approach.png
Labels: cla-not-required, area/docs

#182 Doc fixes for `docs/full/policy.md`
  docs/full/policy.md
Labels: cla-not-required, area/docs

#183 Docs draft cleanup
  docs/full/README.md
  docs/plugindev/design_stage_styleguide_checklist.md
  docs/quickstart/install.md
  docs/quickstart/quickstart.md
Labels: cla-not-required

#184 Mention deprecated commands in quickstart guide
  docs/quickstart/quickstart.md
Labels: cla-not-required

#187 Update main.go template to avoid import-not-used
  cmd/plugin/builder/template/plugintemplates/main.go.tmpl
  docs/plugindev/README.md
Labels: cla-not-required

#188 Disable CEIP prompt for tanzu 'version', 'ceip set' and 'config set' commands
  pkg/command/ceip_participation.go
  pkg/command/root.go
Labels: cla-not-required

#192 Do not show command masked warning for `login` plugin
  pkg/command/root.go
Labels: cla-not-required

#194 Update quickstart for login plugin
  docs/quickstart/quickstart.md
Labels: cla-not-required

#195 Use x86_64 as the correct RPM arch name
  hack/rpm/build_package.sh
  hack/rpm/tanzu-cli.spec
Labels: cla-not-required

#193 Add documentation for test plugin command
  docs/full/cli-architecture.md
  docs/plugindev/README.md
Labels: cla-not-required, area/docs

#197 Update the description of CEIP command with "subject to change"
  pkg/command/ceip_participation.go
Labels: cla-not-required

#196 Check that the context-target-v2 flag is enabled
  pkg/command/plugin.go
Labels: cla-not-required

#198 Update documentation regarding plugin-group and update plugin-tooling to use appropriate variable name
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  docs/quickstart/quickstart.md
  pkg/plugininventory/plugin_inventory.go
  plugin-tooling.mk
Labels: cla-not-required

#199 Update quickstart guide to include usage alongside legacy CLI
  README.md
  docs/quickstart/install.md
  docs/quickstart/quickstart.md
Labels: cla-not-required

#201 Delete entries using unknown target
  pkg/catalog/catalog.go
Labels: cla-not-required

#204 Update release pipeline to support prerelease tag as well
  .github/workflows/release.yaml
Labels: cla-not-required

#205 Use `tanzu-plugin-runtime` v0.90.0-alpha.0
  go.mod
  go.sum
Labels: cla-not-required

#206 Remove mention of admin plugin groups
  docs/plugindev/README.md
  docs/quickstart/quickstart.md
Labels: cla-not-required

#207 Clean up doc markers
  README.md
  docs/plugindev/README.md
Labels: kind/documentation

#208 Update in-development notice
  README.md
Labels: cla-not-required

#214 Add skip signature verification info to plugindev
  docs/plugindev/README.md
Labels: cla-not-required

#215 Update doc regarding `go.mod` update to point to `tanzu-plugin-runtime`
  docs/plugindev/README.md
  docs/plugindev/migrate.md
Labels: cla-not-required

#209 Fix e2e random failures and add stress tests to context use cases
  Makefile
  test/e2e/Makefile
  test/e2e/context/context_k8s_lifecycle_stress_test.go
  test/e2e/context/context_k8s_lifecycle_test.go
  test/e2e/context/context_suite_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_test.go
Labels: cla-not-required

#211 Provide a means to list all versions of a plugin
  pkg/command/plugin_search.go
  pkg/command/plugin_search_test.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#216 Update docs to address the CEIP prompt in automation
  docs/quickstart/install.md
Labels: cla-not-required

#190 Fix the error message for `tanzu plugin install` cmd when all plugins from the group are not mandatory
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#217 Add filtering to the inventory for plugin groups and ignore hidden/deactivated groups
  cmd/plugin/builder/inventory/inventory_plugin_group_test.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/plugininventory/plugin_inventory.go
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_test.go
Labels: cla-not-required

#224 Implement download-bundle, upload-bundle commands to support full migration of plugins
  go.mod
  go.sum
  hack/central-repo/README.md
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/airgapped/plugin_bundle_upload.go
  pkg/airgapped/types.go
  pkg/carvelhelpers/fetcher.go
  pkg/carvelhelpers/image_operations.go
  pkg/carvelhelpers/interface.go
  pkg/carvelhelpers/package.go
  pkg/clientconfighelpers/helpers.go
  pkg/command/plugin.go
  pkg/command/plugin_bundle.go
  pkg/fakes/imageoperationsimpl.go
  pkg/fakes/registy.go
  pkg/registry/client.go
  pkg/registry/interface.go
  pkg/registry/writer.go
Labels: cla-not-required

#220 Upgrade ginkgo to v2
  Makefile
  cmd/plugin/builder/inventory/inventory_init_test.go
  cmd/plugin/builder/inventory/inventory_plugin_group_test.go
  cmd/plugin/builder/inventory/inventory_plugin_test.go
  go.mod
  go.sum
  hack/tools/Makefile
  pkg/airgapped/plugin_bundle_test.go
  pkg/artifact/interface_test.go
  pkg/artifact/local_test.go
  pkg/auth/csp/grpc_test.go
  pkg/auth/tkg/cluster_pinniped_info_test.go
  pkg/auth/tkg/kube_config_test.go
  pkg/auth/utils/kubeconfig/kubeconfig_test.go
  pkg/auth/utils/net/set_port_test.go
  pkg/auth/wcp/discovery_test.go
  pkg/carvelhelpers/package_test.go
  pkg/cluster/client_test.go
  pkg/command/ceip_participation_test.go
  pkg/command/context_test.go
  pkg/command/login_test.go
  pkg/config/bom_test.go
  pkg/config/config_test.go
  pkg/config/defaults_test.go
  pkg/configpaths/filepaths_test.go
  pkg/discovery/kubernetes_test.go
  pkg/discovery/local_test.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/distribution/artifact_test.go
  pkg/plugininventory/sqlite_inventory_test.go
  pkg/pluginsupplier/plugin_supplier_test.go
  pkg/utils/common_test.go
  pkg/utils/files_test.go
  test/e2e/cli_lifecycle/cli_lifecycle_suite_test.go
  test/e2e/cli_lifecycle/init_version_cmds_test.go
  test/e2e/config/config_init_feature_flag_test.go
  test/e2e/config/config_server_test.go
  test/e2e/config/config_suite_test.go
  test/e2e/context/context_k8s_lifecycle_stress_test.go
  test/e2e/context/context_k8s_lifecycle_test.go
  test/e2e/context/context_suite_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/context/tmc/tmc_suite_test.go
  test/e2e/framework/framework.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/plugin_sync_lifecycle_suite_test.go
  test/e2e/plugin_sync/plugin_sync_lifecycle_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_suite_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_test.go
Labels: cla-not-required

#218 Ignore hidden/deactivated plugins
  cmd/plugin/builder/inventory/inventory_plugin_test.go
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/plugininventory/plugin_inventory.go
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_test.go
Labels: cla-not-required

#226 Use log.Warningf() insead of fmt.Printf()
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#228 Move "BeforeSuite" to top-level
  test/e2e/Makefile
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/plugin_sync/plugin_sync_lifecycle_test.go
Labels: cla-not-required

#225 Replace direct access with library config functions for plugin sources
  pkg/command/discovery_source.go
  pkg/command/discovery_source_test.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#222 E2E framework: Setup dynamic tanzu prefix commands
  test/e2e/framework/cli_lifecycle_operations.go
  test/e2e/framework/cmd_exec_operations.go
  test/e2e/framework/config_lifecycle_operations.go
  test/e2e/framework/context_create_operations.go
  test/e2e/framework/context_lifecycle_operations.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/plugin_lifecycle_operations.go
Labels: cla-not-required

#221 make e2e framework as a separate module
  README.md
  go.work
  go.work.sum
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cla-not-required

#219 Provide configuration variable to access deactivated plugins/groups
  cmd/plugin/builder/README.md
  pkg/constants/env_variables.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_test.go
Labels: cla-not-required

#232 Use a plugin source to find the central plugin discovery
  go.mod
  go.sum
  hack/central-repo/README.md
  pkg/command/discovery_source.go
  pkg/command/plugin_search_test.go
  pkg/command/plugin_test.go
  pkg/config/defaults.go
  pkg/config/defaults_test.go
  pkg/config/discovery.go
  pkg/config/discovery_test.go
  pkg/config/init.go
  pkg/constants/env_variables.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_helper_test.go
  pkg/pluginmanager/manager_test.go
  pkg/pluginmanager/test/config-ng.yaml
  pkg/pluginmanager/test/config.yaml
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/framework/framework.go
  test/e2e/framework/output_handling.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/plugin_sync_lifecycle_suite_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_suite_test.go
Labels: cla-not-required

#238 Remove unit test that was no longer relevant
  pkg/config/defaults_test.go
Labels: cla-not-required

#231 Add support for selective plugin migration using plugin groups for air-gapped environments
  go.mod
  go.sum
  go.work.sum
  pkg/airgapped/helper.go
  pkg/airgapped/helper_test.go
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/airgapped/plugin_bundle_upload.go
  pkg/airgapped/types.go
  pkg/carvelhelpers/image_operations.go
  pkg/carvelhelpers/interface.go
  pkg/command/plugin_bundle.go
  pkg/discovery/oci_dbbacked.go
  pkg/fakes/imageoperationsimpl.go
  pkg/fakes/registy.go
  pkg/plugininventory/data/sqlite/plugin_inventory_metadata_tables.sql
  pkg/plugininventory/plugin_inventory.go
  pkg/plugininventory/plugin_inventory_metadata.go
  pkg/plugininventory/sqlite_inventory_metadata.go
  pkg/plugininventory/sqlite_inventory_metadata_test.go
  pkg/plugininventory/sqlite_inventory_schema.go
  pkg/pluginmanager/manager.go
  pkg/registry/client.go
  pkg/registry/interface.go
  pkg/utils/files.go
Labels: cla-not-required
