Repository vmware-tanzu/tanzu-cli, pull requests merged in 2023-12, with the labels that each got.

#607 Document running "brew tap vmware-tanzu/tanzu"
  docs/quickstart/install.md
Labels: cla-not-required

#609 Update the CLI development README
  docs/dev/README.md
Labels: cla-not-required

#608 Add doc to use package managers to upgrade the CLI
  docs/quickstart/install.md
Labels: cla-not-required

#612 Fix indentation in usage line of help of leaf commands
  pkg/cli/usage.go
Labels: cla-not-required, kind/cleanup

#613 Use proper help format for "completion"
  pkg/command/completion.go
  pkg/command/doc.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required, kind/cleanup

#610 Build CLI for Windows ARM64
  Makefile
Labels: cla-not-required, kind/feature

#618 E2E: Install tools as part of E2E tests
  Makefile
Labels: cla-not-required

#604 Refresh the plugin DB on `plugin source init`
  pkg/command/discovery_source.go
  pkg/command/discovery_source_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required, kind/feature

#614 Setup shell completion when installing with Chocolatey
  docs/quickstart/install.md
  hack/choco/chocolateyInstall.ps1.tmpl
Labels: cla-not-required, kind/feature, docs-impact

#611 Build plugins for Windows ARM64
  cmd/plugin/builder/command/cli_compile.go
  cmd/plugin/builder/template/plugintemplates/plugin-tooling.mk.tmpl
  pkg/cli/arch.go
  plugin-tooling.mk
  test/sample-plugin/plugin-tooling.mk
Labels: cla-not-required, kind/feature

#615 Fallback to installing AMD64 plugins on Windows
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_helper_test.go
  pkg/pluginmanager/manager_test.go
Labels: cla-not-required, kind/feature

#617 Build a Chocolatey package that supports ARM64
  Makefile
  hack/choco/README.md
  hack/choco/build_package.sh
  hack/choco/chocolateyInstall.ps1.tmpl
Labels: cla-not-required, kind/feature

#624 Allow for shell vars set to an empty value
  pkg/config/config.go
  pkg/config/config_test.go
Labels: cla-not-required, kind/bug

#605 Add a Time To Live (TTL) to the inventory cache
  docs/dev/centralized_plugin_discovery.md
  pkg/command/discovery_source.go
  pkg/command/discovery_source_test.go
  pkg/constants/env_variables.go
  pkg/discovery/interface.go
  pkg/discovery/oci.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
  test/e2e/Makefile
  test/e2e/airgapped/airgapped_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required, kind/feature, docs-impact
