Repository vmware-tanzu/tanzu-cli, pull requests merged in 2024-02, with the labels that each got.

#665 fix: update chocolatey installer
  hack/choco/chocolateyInstall.ps1.tmpl
Labels: cla-not-required, kind/bug

#666 fix: return error if input file for --to-tar exists
  pkg/airgapped/plugin_bundle_download.go
  test/e2e/airgapped/airgapped_test.go
Labels: cla-not-required, kind/bug

#669 Update spinner to use the updated `NewOutputWriterSpinner` API from plugin runtime
  go.mod
  go.sum
  pkg/pluginmanager/manager.go
Labels: cla-not-required, kind/cleanup

#670 Set verbosity if TANZU_CLI_LOG_LEVEL env variable is set
  pkg/command/root.go
Labels: cla-not-required, kind/bug

#674 Fix the security issue reported on code scan
  pkg/command/root.go
Labels: bug, cla-not-required

#676 Add Skipped state to e2e test summary
  hack/scripts/process-ginkgo-test-results.sh
Labels: cla-not-required

#679 Add new target `operations`/`ops`
  docs/cli/commands/tanzu_plugin_describe.md
  docs/cli/commands/tanzu_plugin_install.md
  docs/cli/commands/tanzu_plugin_search.md
  docs/cli/commands/tanzu_plugin_uninstall.md
  docs/cli/commands/tanzu_plugin_upgrade.md
  docs/full/README.md
  docs/quickstart/quickstart.md
  go.mod
  go.sum
  pkg/command/completion_helper.go
  pkg/command/plugin.go
  pkg/command/plugin_search.go
  pkg/command/plugin_search_test.go
  pkg/command/plugin_test.go
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/common/constants.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required

#682 Update test-central-plugin-repository with `operations` target plugin and update E2E
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  test/e2e/airgapped/airgapped_test.go
  test/e2e/airgapped/plugins.go
  test/e2e/config_data/input_data.yaml
Labels: cla-not-required

#684 Move Dockerfile from root to test/e2e/coexistence
  .github/workflows/cli-coexistence_tests.yaml
  .gitignore
  Makefile
  test/e2e/coexistence/Dockerfile
Labels: cla-not-required
