Repository vmware-tanzu/tanzu-cli, pull requests merged in 2024-05, with the labels that each got.

#753 Conditionally enable active context type check for plugin override
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/constants/featureflags.go
Labels: cla-not-required, docs-impact

#755 Switch default discovery source registry to `projects.packages.broadcom.com`
  docs/cli/commands/tanzu_plugin_download-bundle.md
  pkg/config/config.go
  pkg/constants/defaults.go
  pkg/globalinit/plugin_discovery_source_update.go
Labels: cla-not-required

#756 Bump `github.com/docker/docker` and `golang.org/x/net` dependencies
  Makefile
  go.mod
  go.sum
  test/e2e/framework/go.mod
  test/e2e/framework/go.sum
  test/sample-plugin/go.mod
  test/sample-plugin/go.sum
Labels: cla-not-required, dependencies

#734 Experimental: Set the Tanzu Hub endpoint when creating `tanzu` context
  go.mod
  go.sum
  pkg/auth/csp/tanzu.go
  pkg/command/context.go
Labels: cla-not-required

#758 Update EULA
  pkg/config/config.go
Labels: cla-not-required

#760 Update error for Broadcom Foundation Agreement
  pkg/command/eula_test.go
  pkg/command/root.go
Labels: cla-not-required

#761 Include a new cosign public key to verify the images
  pkg/cosignhelper/cosignverify.go
  pkg/cosignhelper/tanzu_cli_cert.go
Labels: cla-not-required

#763 Update kb article in security disclosure section
  SECURITY.md
Labels: cla-not-required

#762 Add placeholder tpe command group
  docs/plugindev/README.md
  pkg/command/root.go
  pkg/command/root_test.go
Labels: cla-not-required

#765 Add test cases for tpe command group
  pkg/command/root_test.go
Labels: cla-not-required

#764 Experimental: Get the Tanzu Hub Endpoint based on the Central Config Metadata
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/auth/csp/tanzu.go
  pkg/command/context.go
Labels: cla-not-required

#766 Cleanup help text for `tanzu context create` command
  pkg/command/context.go
Labels: cla-not-required

#769 Use shared values of latest version of plugins
  pkg/plugininventory/sqlite_inventory.go
  pkg/plugininventory/sqlite_inventory_test.go
Labels: cla-not-required

#770 Remove warning message regarding the current kubecontext while deleting the tanzu context
  pkg/auth/utils/kubeconfig/kubeconfig.go
Labels: cla-not-required

#771 login and context create commands informs user when `TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID` is being used
  pkg/command/context.go
Labels: cla-not-required

#773 Hide the init command
  pkg/command/init.go
Labels: cla-not-required

#775 Fix indentation for example
  pkg/command/login.go
Labels: cla-not-required

#776 Document details of support for ARM64
  docs/quickstart/install.md
Labels: cla-not-required
