Repository vmware-tanzu/tanzu-cli, pull requests merged in 2024-04, with the labels that each got.

#724 Add `operations` target to docs
  docs/full/cli-architecture.md
Labels: cla-not-required

#721 Update the UX for "context use" and "context list" commands to show ProjectID details
  pkg/command/context.go
  pkg/command/context_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
Labels: cla-not-required

#714 Document the user-facing CLI environment variables
  docs/full/README.md
  docs/quickstart/quickstart.md
Labels: cla-not-required, kind/documentation, docs-impact

#713 Fix the documentation for ActiveHelp
  docs/full/README.md
  pkg/constants/env_variables.go
Labels: cla-not-required, kind/cleanup

#716 Document the CLI environment variables used for testing
  docs/dev/README.md
  docs/full/README.md
Labels: cla-not-required, kind/documentation, docs-impact

#727 Provide documentation link in upgrade message
  pkg/recommendedversion/recommended_version.go
Labels: cla-not-required

#725 Add support for individual plugin download with `tanzu plugin download-bundle` command
  docs/quickstart/install.md
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/command/plugin_bundle.go
  pkg/command/plugin_bundle_test.go
  pkg/plugininventory/plugin_inventory.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/airgapped/plugins.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/output_handling.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_helper.go
Labels: cla-not-required, kind/feature, docs-impact

#729 Skip plugin-group verification when TANZU_CLI_SKIP_PLUGIN_GROUP_VERIF…
  pkg/constants/env_variables.go
  pkg/plugininventory/sqlite_inventory.go
Labels: cla-not-required

#726 Add support to address the multiple callback requests during redirect by browser during login
  pkg/auth/csp/tanzu.go
Labels: cla-not-required

#715 Update the tanzu login command to log in to TAP SaaS
  docs/quickstart/quickstart.md
  pkg/command/ceip_participation_test.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/login.go
  pkg/command/login_test.go
Labels: cla-not-required, docs-impact

#732 Enable tests that were not being run
  pkg/config/config_test.go
Labels: cla-not-required

#728 Add --refresh-configuration-only to download-bundle
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/command/plugin_bundle.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/framework/plugin_lifecycle_operations.go
Labels: cla-not-required

#735 Update signal handling logic
  go.mod
  go.sum
  pkg/command/root.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#723 Setup global initializer for missing central config file
  docs/dev/README.md
  docs/full/README.md
  pkg/centralconfig/central_config.go
  pkg/centralconfig/central_config_cache_init.go
  pkg/centralconfig/central_config_cache_init_test.go
  pkg/centralconfig/central_config_test.go
  pkg/command/discovery_source.go
  pkg/command/plugin_helper_test.go
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/constants/defaults.go
  pkg/discovery/interface.go
  pkg/discovery/oci.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/discovery/utils.go
  pkg/globalinit/global_initializers.go
  pkg/globalinit/global_initializers_test.go
  test/e2e/centralconfig/central_config_suite_test.go
  test/e2e/cli_lifecycle/initialize_central_config_test.go
Labels: cla-not-required, kind/feature, docs-impact

#698 Unify the plugin installation for standalone and context-scoped plugins and use context as recommendation
  .gitignore
  cmd/plugin/test/main.go
  docs/dev/README.md
  docs/full/README.md
  docs/full/cli-architecture.md
  docs/full/context-recommended-plugins.md
  docs/plugindev/README.md
  docs/quickstart/quickstart.md
  go.mod
  go.sum
  go.work.sum
  pkg/catalog/cleanup.go
  pkg/command/context.go
  pkg/command/context_tkg_helper.go
  pkg/command/login.go
  pkg/command/plugin.go
  pkg/command/plugin_group.go
  pkg/command/plugin_helper_test.go
  pkg/command/plugin_search.go
  pkg/command/plugin_test.go
  pkg/constants/env_variables.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_helper_test.go
  pkg/pluginmanager/manager_test.go
  pkg/pluginsupplier/plugin_supplier.go
  pkg/pluginsupplier/plugin_supplier_test.go
  test/e2e/framework/framework_constants.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/output_handling.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required, docs-impact

#737 Add null pointer checks for context fields
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/telemetry/metrics_helper.go
Labels: cla-not-required

#731 Add support to check if the selected org is Tanzu Application platform enabled
  hack/central-repo/registry-content.bz2
  hack/central-repo/upload-plugins.sh
  pkg/auth/utils/kubeconfig/kubeconfig.go
  pkg/centralconfig/central_config_yaml_reader.go
  pkg/command/context.go
  pkg/command/org_validation_helper.go
  pkg/command/org_validation_helper_test.go
  pkg/constants/env_variables.go
  pkg/pluginmanager/manager.go
Labels: cla-not-required

#738 Perform a catalog initialization if needed
  pkg/command/plugin_search_test.go
  pkg/command/plugin_test.go
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/config/defaults_test.go
  pkg/config/discovery_test.go
  pkg/config/init.go
  pkg/config/init_test.go
  pkg/constants/featureflags.go
  pkg/discovery/oci_test.go
  pkg/globalinit/catalog_cache_init.go
  pkg/lastversion/last_version.go
  pkg/lastversion/last_version_test.go
Labels: cla-not-required

#743 Allow turning off go's buildvcs
  Makefile
Labels: cla-not-required

#744 Add support for the Authenticated Registries
  docs/dev/README.md
  pkg/carvelhelpers/fetcher.go
  pkg/constants/env_variables.go
  pkg/utils/url.go
  pkg/utils/url_test.go
  test/e2e/airgapped/airgapped_suite_test.go
  test/e2e/airgapped/airgapped_test.go
Labels: cla-not-required, docs-impact

#745 Air-gap: document --refresh-configuration-only
  docs/quickstart/install.md
Labels: cla-not-required, docs-impact

#751 Fix cosign verification issue for the Authenticated registry
  pkg/cosignhelper/cosignverify.go
Labels: cla-not-required

#746 Update kubecontext name associated with `tanzu` CLI Context when active resource is updated
  docs/full/README.md
  pkg/auth/tanzu/kubeconfig.go
  pkg/auth/tanzu/kubeconfig_test.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/command/login.go
  pkg/constants/env_variables.go
Labels: cla-not-required, docs-impact

#748 Fix setting of invocation context env vars on mapped targeted commands
  pkg/cli/plugin_cmd.go
  pkg/command/root_test.go
Labels: cla-not-required

#754 Ignore command PreRun logic for tanzu context get-token command
  pkg/command/root.go
Labels: cla-not-required

#747 Use internal Kubeconfig file instead of default kubeconfig to store kubecontext for TAP SaaS
  pkg/auth/tanzu/kubeconfig.go
  pkg/auth/tanzu/kubeconfig_test.go
Labels: cla-not-required, docs-impact
