Repository vmware-tanzu/tanzu-cli, pull requests merged in 2024-01, with the labels that each got.

#627 Add interactive(browser) login support for 'tanzu' context creation
  apis/cli/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/auth/csp/selfmanaged.go
  pkg/auth/csp/selfmanaged_test.go
  pkg/auth/csp/tanzu.go
  pkg/auth/csp/tanzu_test.go
  pkg/auth/csp/token.go
  pkg/auth/csp/token_test.go
  pkg/command/context.go
  pkg/command/context_test.go
  pkg/constants/env_variables.go
Labels: documentation, cla-not-required

#631 Update the tanzu context create command help
  pkg/command/context.go
Labels: cla-not-required

#633 Fix e2e test for tanzu context create command help
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
Labels: cla-not-required

#628 UX updates to `tanzu context list` and `tanzu context use` command outputs
  .gitignore
  go.work.sum
  pkg/command/context.go
  pkg/command/context_test.go
Labels: cla-not-required, area/ux, kind/feature, docs-impact

#636 Fix log message on activating context when project/space/clustergroup keys not exists in config
  pkg/command/context.go
Labels: cla-not-required, kind/bug

#626 Hide a target command that has no plugins
  docs/full/README.md
  pkg/cli/usage.go
  pkg/command/root.go
  pkg/command/root_test.go
Labels: cla-not-required, kind/bug

#639 update test/e2e/framework runtime dep to 1.2.0-alpha.0
  test/e2e/framework/go.mod
  test/e2e/framework/go.sum
Labels: cla-not-required

#640 Update runtime dep to 1.2.0-alpha.0
  go.mod
  go.sum
Labels: cla-not-required

#632 Properly handle CLIPlugin resources when different k8s namespaces return same plugin
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
Labels: cla-not-required, kind/bug

#630 Fix the `tanzu plugin download-bundle` when same plugin is part of multiple plugin-groups
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/plugininventory/plugin_inventory.go
  pkg/plugininventory/plugin_inventory_test.go
  test/e2e/airgapped/airgapped_test.go
Labels: cla-not-required, kind/bug

#622 Warn user of shadowed variables on "config get"
  pkg/command/config.go
  pkg/command/config_test.go
  test/e2e/config/config_suite_test.go
  test/e2e/framework/framework_constants.go
Labels: cla-not-required, kind/feature

#642 Allow listing the CLIPlugins resources even if the CRD discovery API returns an error for the kubernetes context
  pkg/discovery/kubernetes.go
  pkg/discovery/kubernetes_test.go
Labels: cla-not-required, kind/bug

#644 Merge plugin-group manifest automatically when building individual plugins with the `builder` plugin
  cmd/plugin/builder/command/cli_compile.go
  cmd/plugin/builder/command/cli_compile_test.go
Labels: cla-not-required

#647 Enable previously disabled linters like nakedret, revive unparam, gosec from golang-cli.yml
  .golangci.yaml
  cmd/plugin/builder/command/publish/helper_test.go
  cmd/plugin/builder/inventory/inventory_plugin_group_test.go
  cmd/plugin/builder/inventory/inventory_plugin_test.go
  cmd/plugin/test/test/main.go
  cmd/tanzu/main.go
  pkg/airgapped/plugin_bundle_download.go
  pkg/airgapped/plugin_bundle_test.go
  pkg/auth/csp/grpc.go
  pkg/auth/tkg/kube_config.go
  pkg/carvelhelpers/package.go
  pkg/carvelhelpers/ytt.go
  pkg/command/ceip_participation.go
  pkg/command/cert.go
  pkg/command/completion_helper.go
  pkg/command/config.go
  pkg/command/context.go
  pkg/command/discovery_source.go
  pkg/command/login.go
  pkg/command/plugin_bundle.go
  pkg/command/plugin_group.go
  pkg/command/root.go
  pkg/command/root_test.go
  pkg/cosignhelper/cosignverify.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/discovery/rest.go
  pkg/plugincmdtree/plugins_cache_test.go
  pkg/plugininventory/sqlite_inventory.go
  pkg/pluginmanager/manager.go
  pkg/pluginmanager/manager_test.go
  pkg/telemetry/client_test.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required, kind/cleanup

#649 Add show details reminder in group search output
  pkg/command/plugin_group.go
  pkg/command/plugin_group_test.go
Labels: cla-not-required, kind/feature

#646 UX: Sort plugin list and plugin search output by plugin name
  pkg/cli/plugin_info.go
  pkg/command/plugin.go
  pkg/discovery/types.go
  test/e2e/framework/framework_constants.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_helper.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_helper.go
Labels: cla-not-required

#643 Remove deprecated components
  apis/cli/v1alpha1/cliplugin_types.go
  apis/config/crd/bases/cli.tanzu.vmware.com_cliplugins.yaml
  cmd/plugin/builder/README.md
  cmd/plugin/builder/cli.go
  cmd/plugin/builder/command/publish.go
  cmd/plugin/builder/command/publish/helper.go
  cmd/plugin/builder/command/publish/helper_test.go
  cmd/plugin/builder/command/publish/local.go
  cmd/plugin/builder/command/publish/oci.go
  cmd/plugin/builder/command/publish/publisher.go
  cmd/plugin/builder/main.go
  cmd/plugin/builder/publish.go
  docs/full/cli-architecture.md
  docs/quickstart/quickstart.md
  go.mod
  pkg/command/config.go
  pkg/command/config_test.go
  pkg/common/constants.go
  pkg/config/bom.go
  pkg/config/bom_test.go
  pkg/config/defaults.go
  pkg/config/edition.go
  pkg/config/edition_test.go
  pkg/config/features_test.go
  pkg/config/init.go
  pkg/discovery/utils.go
  pkg/discovery/utils_test.go
  pkg/distribution/interface.go
  pkg/fakes/config/tanzu_config.yaml
  pkg/fakes/config/tanzu_config_ng.yaml
  pkg/fakes/config/tanzu_config_ng_2.yaml
  pkg/fakes/config/tanzu_config_yaml.tmpl
  pkg/pluginmanager/manager_test.go
  test/e2e/config/config_server_test.go
  test/e2e/config_data/cli.tanzu.vmware.com_cliplugins.yaml
  test/e2e/framework/config_lifecycle_operations.go
  test/e2e/framework/framework_constants.go
  test/e2e/framework/framework_helper.go
  test/e2e/framework/plugin_operations.go
Labels: cla-not-required, kind/cleanup

#650 UX: Sort context list output by context name
  go.mod
  go.sum
  pkg/command/context.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/context_lifecycle_operations.go
  test/e2e/framework/framework_helper.go
Labels: cla-not-required, kind/feature

#645 Add support for interactive login on terminal based hosts(without browser) for tanzu context
  go.mod
  pkg/auth/csp/tanzu.go
  pkg/auth/csp/tanzu_test.go
  pkg/auth/csp/token.go
  pkg/auth/tanzu/kubeconfig.go
  pkg/command/context.go
  pkg/constants/env_variables.go
Labels: documentation, cla-not-required

#652 Clear all the local metrics data when user opt out of CEIP
  pkg/telemetry/client.go
  pkg/telemetry/client_test.go
  pkg/telemetry/metric_db.go
  pkg/telemetry/sqlite_metrics_db.go
Labels: cla-not-required

#637 Implement refresh of database cache based on digest timestamp
  pkg/command/root.go
  pkg/constants/defaults.go
  pkg/constants/env_variables.go
  pkg/discovery/utils.go
  test/e2e/cataloge2e/catalog_update_parallel_test.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required, kind/feature

#648 Show the CSP Organization name in the browser after successful CSP login
  pkg/auth/csp/tanzu.go
  pkg/auth/csp/tanzu_test.go
Labels: cla-not-required

#655 Update docs with "tanzu" context creation
  docs/quickstart/images/interactive_login_copy_authcode.png
  docs/quickstart/quickstart.md
  pkg/command/context.go
Labels: documentation, cla-not-required, kind/documentation

#651 Support context-scoped plugin discovery for `tanzu` contexts behind feature-flag
  go.mod
  go.sum
  pkg/cluster/client.go
  pkg/cluster/client_test.go
  pkg/constants/defaults.go
  pkg/constants/env_variables.go
  pkg/constants/featureflags.go
  pkg/discovery/interface.go
  pkg/discovery/kubernetes.go
  pkg/fakes/clusterclientfactory_fake.go
  pkg/pluginmanager/default_discoveries.go
  pkg/pluginmanager/default_discoveries_test.go
  pkg/pluginmanager/test/kubeconfig.yaml
Labels: cla-not-required, kind/feature

#658 change: UX: Sort context unset and delete output by plugin name
  pkg/command/context.go
Labels: cla-not-required, kind/feature

#653 UX: Sort context create and context use output by context name
  pkg/command/context.go
  test/e2e/context/k8s/context_k8s_lifecycle_test.go
  test/e2e/context/tmc/context_tmc_lifecycle_test.go
  test/e2e/framework/context_create_operations.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
  test/sample-plugin/cmd/plugin/sample-plugin/test/e2e/framework_functionality/plugin_functionality_test.go
Labels: cla-not-required, kind/feature

#641 UX: Add in-progress spinner for plugin installation
  go.work.sum
  pkg/pluginmanager/manager.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/cataloge2e/catalog_update_parallel_test.go
  test/e2e/coexistence/cli_coexistence_test.go
  test/e2e/framework/plugin_lifecycle_operations.go
  test/e2e/plugin_lifecycle/plugin_group_lifecycle_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_suite_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
  test/e2e/plugin_sync/k8s/plugin_sync_k8s_lifecycle_test.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
  test/e2e/plugins_compatibility/plugins_compatibility_test.go
Labels: cla-not-required

#659 Fix e2e plugin sync tmc test
  test/e2e/framework/framework_helper.go
  test/e2e/plugin_sync/tmc/plugin_sync_tmc_lifecycle_test.go
Labels: cla-not-required

#660 Fix: Catch the interrupt signal when spinner is running
  pkg/pluginmanager/manager.go
Labels: cla-not-required, kind/bug

#664 Change TANZU_CLI_PLUGIN_DB_CACHE_REFRESH_THRESHOLD to TANZU_CLI_PLUGIN_DB_CACHE_REFRESH_THRESHOLD_SECONDS
  pkg/constants/defaults.go
  pkg/constants/env_variables.go
  pkg/discovery/oci_dbbacked.go
  pkg/discovery/oci_dbbacked_test.go
  pkg/discovery/utils.go
  test/e2e/airgapped/airgapped_test.go
  test/e2e/plugin_lifecycle/plugin_lifecycle_test.go
Labels: cla-not-required

#663 Fix cert update by making certificate fields mutually exclusive
  pkg/command/cert.go
  pkg/command/cert_test.go
Labels: cla-not-required
